export enum BrickName {
  RED = "RED",
  PINK = "PINK",
  PURPLE = "PURPLE",
  WOOD = "WOOD",
  AUBERGINE = "AUBERGINE",
  ULTRAMARINE = "ULTRAMARINE",
  COPPER = "COPPER",
  BLUE_LIGHT = "BLUE_LIGHT",
  CYAN = "CYAN",
  TEAL = "TEAL",
  STEEL = "STEEL",
  GREEN = "GREEN",
  LIME = "LIME",
  LEMON = "LEMON",
  LEMON_ICE = "LEMON_ICE",
  BRICK = "BRICK",
  BROWN = "BROWN",
  IRON = "IRON",
  ICE = "ICE",
  BLUE_DARK = "BLUE_DARK",
  YELLOW = "YELLOW",
  ORANGE_LIGHT = "ORANGE_LIGHT",
  ORANGE_DARK = "ORANGE_DARK",
  PETROL = "PETROL",
}

export const brickNames: BrickName[] = [
  BrickName.BRICK,
  BrickName.BROWN,
  BrickName.COPPER,
  BrickName.CYAN,
  BrickName.ICE,
  BrickName.IRON,
  BrickName.STEEL,
  BrickName.WOOD,
  BrickName.YELLOW,
]; //Object.values(BrickName);
