export enum BrickName {
  RED = "RED",
  PINK = "PINK",
  PURPLE = "PURPLE",
  WOOD = "WOOD",
  AUBERGINE = "AUBERGINE",
  ULTRAMARINE = "ULTRAMARINE",
  COPPER = "COPPER",
  BLUE_LIGHT = "BLUE_LIGHT",
  CYAN = "CYAN",
  TEAL = "TEAL",
  STEEL = "STEEL",
  GREEN = "GREEN",
  LIME = "LIME",
  LEMON = "LEMON",
  LEMON_ICE = "LEMON_ICE",
  BRICK = "BRICK",
  BROWN = "BROWN",
  IRON = "IRON",
  ICE = "ICE",
  BLUE_DARK = "BLUE_DARK",
  YELLOW = "YELLOW",
  ORANGE_LIGHT = "ORANGE_LIGHT",
  ORANGE_DARK = "ORANGE_DARK",
  PETROL = "PETROL",
}

export const brickNames: BrickName[] = [
  // BrickName.BRICK,
  // BrickName.BROWN,
  // BrickName.COPPER,
  // BrickName.PETROL,
  // BrickName.ICE,
  // BrickName.IRON,
  // BrickName.STEEL,
  // BrickName.WOOD,
  BrickName.LEMON_ICE,
  // BrickName.TEAL,
  // BrickName.BLUE_LIGHT,
  // BrickName.ULTRAMARINE,
  // BrickName.GREEN,
  // BrickName.ORANGE_DARK,
  // BrickName.AUBERGINE,
  //BrickName.BLUE_DARK,
]; //Object.values(BrickName);

/* OLD NAMES

export enum BrickName {
  RED = 'brick-red',
  PINK = 'brick-pink',
  PURPLE = 'brick-purple',
  PURPLE_DARK = 'brick-dpurple',
  BLUE = 'brick-blue',
  BLUE_DARK = 'brick-dblue',
  BLUE_ICE = 'brick-iceblue',
  GREEN_DARK = 'brick-algae',
  GREEN_LIGHT = 'brick-lime',
  YELLOW = 'brick-yellow',
  GOLD = 'brick-gold',
  RED_DARK = 'brick-brickred',
  BROWN = 'brick-brown',
  BLUE_MID = 'brick-discordblue',
  YELLOW_SUN = 'brick-sunyellow',
  ORANGE = 'brick-orange',
  ORANGE_DARK = 'brick-dorange',
  WOOD = 'brick-wood',
  COPPER = 'brick-copper',
  IRON = 'brick-iron',
  STONE = 'brick-stone',
  DIAMON = 'brick-diamond',
  GLASS = 'brick-glass',
}

*/
